version: "3.8"

services:
  database:
    image: postgres
    container_name: db_demen
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=demen
    volumes:
      - pgdata:/data/postgres

  app:
    build:
      context: .
      target: production
    container_name: demen-prod-server
    ports:
      - 3334:3334
    environment:
      - NODE_ENV=production
      - PORT=3334
      - TYPEORM_ENTITIES="./dist/modules/**/infra/typeorm/entities/*.js"
      - TYPEORM_MIGRATIONS="./dist/shared/infra/typeorm/migrations/*.js"
      - MIGRATIONS_DIR="./dist/shared/infra/typeorm/migrations"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
