version: "3.8"

services:
  database:
    image: postgres
    container_name: db_demen
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=demen
      - POSTGRES_DB=demen
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: demen-server
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
