version: "3.8"

services:
  database:
    image: postgres
    container_name: db_demen
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=demen
      - POSTGRES_DB=demen
    volumes:
      - pgdata:/data/postgres

  app-dev:
    build:
      context: .
      target: development
    container_name: demen-dev-server
    ports:
      - 3333:3333
      - 9229:9229
    environment:
      - NODE_ENV=development
      - PORT=3333
      - TYPEORM_ENTITIES=./dist/modules/**/infra/typeorm/entities/*.js
      - TYPEORM_MIGRATIONS=./dist/shared/infra/typeorm/migrations/*.js
      - MIGRATIONS_DIR=./dist/shared/infra/typeorm/migrations
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

  app-prod:
    build:
      context: .
      target: production
    container_name: demen-prod-server
    ports:
      - 3334:3334
    environment:
      - NODE_ENV=production
      - PORT=3334
      - TYPEORM_ENTITIES="./dist/modules/**/infra/typeorm/entities/*.js"
      - TYPEORM_MIGRATIONS="./dist/shared/infra/typeorm/migrations/*.js"
      - MIGRATIONS_DIR="./dist/shared/infra/typeorm/migrations"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
