openapi: 3.0.0
info:
  title: API Democratizando o Ensino
  description: Documentação da API
  version: 0.0.1

paths:
  /accounts/users:
    post:
      tags:
        - Users
      summary: Criação de Usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/UserDto"
      responses:
        201:
          description: 'Sucesso!'
          content:
            application/json:
              schema:
                $ref: "#/definitions/User"
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"


definitions:
  Error:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    example:
      message: Something went wrong!
      status: error
  User:
    type: object
    properties:
        username:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
    example:
      username: foobar
      email: foobar@example.com
      name: Foo
      lastName: Bar
      createdAt: 01/01/1111
      updatedAt: 01/01/1111
  UserDto:
    type: object
    properties:
        username:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        lastName:
          type: string
        password:
          type: string
          format: secret
    example:
      username: foobar
      email: foobar@example.com
      name: Foo
      lastName: Bar
      password: "*****"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

