openapi: 3.0.0
info:
  title: API Democratizando o Ensino
  description: Documentação da API
  version: 0.0.1

paths:
  /accounts/users:
    post:
      tags:
        - Users
      summary: Criação de Usuário
      description: Rota para criação de usuários.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/UserDto"
      responses:
        201:
          description: 'Sucesso!'
          content:
            application/json:
              schema:
                $ref: "#/definitions/User"
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"

  /accounts/sessions:
    post:
      tags:
        - Sessions
      summary: Criação de sessão
      description: Rota para login de usuários.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/Login"
      responses:
        201:
          description: 'Sucesso!'
          content:
            application/json:
              schema:
                $ref: "#/definitions/Session"

        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"

definitions:
  Session:
    type: object
    properties:
      user:
        $ref: "#/definitions/SessionUser"
      token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw

  Error:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    example:
      message: Something went wrong!
      status: error

  User:
    type: object
    properties:
        username:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
    example:
      username: foobar
      email: foobar@example.com
      name: Foo
      lastName: Bar
      createdAt: 01/01/1111
      updatedAt: 01/01/1111

  SessionUser:
    allOf:
      - $ref: "#/definitions/User"
      - type: object
        properties:
          id:
            type: string
            format: uuid
        example:
          id: adf8df02-cc28-4c46-9fde-ded8c574f24f

  UserDto:
    type: object
    properties:
        username:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        lastName:
          type: string
        password:
          type: string
          format: secret
    example:
      username: foobar
      email: foobar@example.com
      name: Foo
      lastName: Bar
      password: "*****"

  Login:
    type: object
    properties:
      email:
          type: string
          format: email
      password:
          type: string
          format: secret
    example:
      email: foobar@example.com
      password: "*****"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

